import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import NavBar from "@/components/shared/nav-bar";
import { Toaster } from "sonner";
import SessionProvider from "@/components/shared/session-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <EdgeStoreProvider>
          <body className={cn("relative", inter.className)}>
            {children}
            <Toaster richColors />
          </body>
        </EdgeStoreProvider>
      </SessionProvider>
    </html>
  );
}
